### ISSUE TITLE
Invalid JSON when task error occurs

### ISSUE THREAD

**Issue by laurentpellegrino** [ow2-proactive/cloud-automation#1]
<a href="https://jira.activeeon.com/browse/SCHEDULING-2482" title="SCHEDULING-2482">Original issue</a> created by <a href="mailto:fabien.viale_AT_activeeon.com">Fabien Viale</a> on 26, Mar 2015 at 14:03 PM - SCHEDULING-2482

<hr />

The value of the TaskNearest returned should be a String (surrounded with double quotes). Internal double quotes should be escaped.

Here is an example of what is currently returned:

```
{
                "results":
                {
                               "TaskNearest":org.ow2.proactive.scheduler.common.exception.UserException: Script has failed on the current node
                               at org.ow2.proactive.scheduler.task.script.ScriptExecutable.execute(ScriptExecutable.java:111)
                               at org.ow2.proactive.scheduler.task.TaskLauncher$ExecutableGuard$9.call(TaskLauncher.java:1910)
                               at org.ow2.proactive.scheduler.task.TaskLauncher$ExecutableGuard$9.call(TaskLauncher.java:1905)
                               at org.ow2.proactive.scheduler.task.utils.ActiveObjectExecutor.call(ActiveObjectExecutor.java:102)
                               at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                               at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
                               at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
                               at java.lang.reflect.Method.invoke(Unknown Source)
                               at org.objectweb.proactive.core.mop.MethodCall.execute(MethodCall.java:355)
                               at org.objectweb.proactive.core.body.request.RequestImpl.serveInternal(RequestImpl.java:216)
                               at org.objectweb.proactive.core.body.request.RequestImpl.serve(RequestImpl.java:162)
                              at org.objectweb.proactive.core.body.BodyImpl$ActiveLocalBodyStrategy.serveInternal(BodyImpl.java:553)
                               at org.objectweb.proactive.core.body.BodyImpl$ActiveLocalBodyStrategy.serve(BodyImpl.java:486)
                               at org.objectweb.proactive.core.body.AbstractBody.serve(AbstractBody.java:428)
                               at org.objectweb.proactive.Service.blockingServeOldest(Service.java:206)
                               at org.objectweb.proactive.Service.blockingServeOldest(Service.java:181)
                               at org.objectweb.proactive.Service.fifoServing(Service.java:146)
                               at org.objectweb.proactive.core.body.ActiveBody$FIFORunActive.runActivity(ActiveBody.java:273)
                               at org.objectweb.proactive.core.body.ActiveBody.run(ActiveBody.java:166)
                               at java.lang.Thread.run(Unknown Source)
                               Caused by: java.lang.Exception: Error: Error in data.frame("644834", "607415", "616914", "614326", "B1526400", : arguments imply differing number of rows: 1, 0
                               Call Stack : 
                               data.frame("644834", "607415", "616914", "614326", "B1526400", NULL, NULL, NULL, "C21727756", "C21727720", "639108", "634189", "C20415767", "702484", "702446", "677773", check.names = FALSE, stringsAsFactors = TRUE)
                               eval(expr, envir, enclos)
                               eval(as.call(c(expression(data.frame), x, check.names = !optional, stringsAsFactors = stringsAsFactors)))
                               as.data.frame.list(x(link: [i]), optional = TRUE, stringsAsFactors = stringsAsFactors)
                               as.data.frame(x(link: [i]), optional = TRUE, stringsAsFactors = stringsAsFactors)
                               data.frame(CONCENTRATION = c(0.02, 1.33, 4.16, 4.2, 0.5, 1.1, 52.09, 25, 0.225, 0.075, 1, 1, 3, 1, 5, 0.3), MAT_ID = list("644834", "607415", "616914", "614326", "B1526400", NULL, NULL, NULL, "C21727756", "C21727720", "639108", "634189", "C20415767", "702484", "702446", "677773"), check.names = FALSE, stringsAsFactors = TRUE)
                               eval(expr, envir, enclos

                              javax.script.ScriptException: Error: Error in data.frame("644834", "607415", "616914", "614326", "B1526400", : arguments imply differing number of rows: 1, 0
                               Call Stack : 
                               data.frame("644834", "607415", "616914", "614326", "B1526400", NULL, NULL, NULL, "C21727756", "C21727720", "639108", "634189", "C20415767", "702484", "702446", "677773", check.names = FALSE, stringsAsFactors = TRUE)
                               eval(expr, envir, enclos)
                               eval(as.call(c(expression(data.frame), x, check.names = !optional, stringsAsFactors = stringsAsFactors)))
                               as.data.frame.list(x(link: [i]), optional = TRUE, stringsAsFactors = stringsAsFactors)
                               as.data.frame(x(link: [i]), optional = TRUE, stringsAsFactors = stringsAsFactors)
                               data.frame(CONCENTRATION = c(0.02, 1.33, 4.16, 4.2, 0.5, 1.1, 52.09, 25, 0.225, 0.075, 1, 1, 3, 1, 5, 0.3), MAT_ID = list("644834", "607415", "616914", "614326", "B1526400", NULL, NULL, NULL, "C21727756", "C21727720", "639108", "634189", "C20415767", "702484", "702446", "677773"), check.names = FALSE, stringsAsFactors = TRUE)
                               eval(expr, envir, enclos
                               at org.ow2.parscript.PARScriptEngine.eval(PARScriptEngine.java:144)
                               at org.ow2.parscript.PARScriptEngine.eval(PARScriptEngine.java:202)
                               at javax.script.AbstractScriptEngine.eval(Unknown Source)
                               at org.ow2.proactive.scripting.Script.execute(Script.java:324)
                               at org.ow2.proactive.scripting.ScriptHandler.handle(ScriptHandler.java:75)
                               at org.ow2.proactive.scheduler.task.script.ScriptExecutable.execute(ScriptExecutable.java:106)
                               at org.ow2.proactive.scheduler.task.TaskLauncher$ExecutableGuard$9.call(TaskLauncher.java:1910)
                               at org.ow2.proactive.scheduler.task.TaskLauncher$ExecutableGuard$9.call(TaskLauncher.java:1905)
                               at org.ow2.proactive.scheduler.task.utils.ActiveObjectExecutor.call(ActiveObjectExecutor.java:102)
                               at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                               at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
                               at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
                               at java.lang.reflect.Method.invoke(Unknown Source)
                               at org.objectweb.proactive.core.mop.MethodCall.execute(MethodCall.java:355)
                               at org.objectweb.proactive.core.body.request.RequestImpl.serveInternal(RequestImpl.java:216)
                               at org.objectweb.proactive.core.body.request.RequestImpl.serve(RequestImpl.java:162)
                              at org.objectweb.proactive.core.body.BodyImpl$ActiveLocalBodyStrategy.serveInternal(BodyImpl.java:553)
                               at org.objectweb.proactive.core.body.BodyImpl$ActiveLocalBodyStrategy.serve(BodyImpl.java:486)
                               at org.objectweb.proactive.core.body.AbstractBody.serve(AbstractBody.java:428)
                               at org.objectweb.proactive.Service.blockingServeOldest(Service.java:206)
                               at org.objectweb.proactive.Service.blockingServeOldest(Service.java:181)
                               at org.objectweb.proactive.Service.fifoServing(Service.java:146)
                               at org.objectweb.proactive.core.body.ActiveBody$FIFORunActive.runActivity(ActiveBody.java:273)
                               at org.objectweb.proactive.core.body.ActiveBody.run(ActiveBody.java:166)
                               at java.lang.Thread.run(Unknown Source)

                               at org.ow2.proactive.scripting.Script.execute(Script.java:341)
                               at org.ow2.proactive.scripting.ScriptHandler.handle(ScriptHandler.java:75)
                               at org.ow2.proactive.scheduler.task.script.ScriptExecutable.execute(ScriptExecutable.java:106)
                               ... 19 more

                }
}
```

**Comment by fviale** [comment]
In order to reproduce it:
1) install the workflow-catalog war in the scheduler dist/war folder
2) create a workflow containing a single task which throws an error and put in the catalog folder
3) from a REST client, after authenticating to the workflow-catalog (workflow-catalog/wc/login), call the POST request "workflow-catalog/wc/workflow" with JSON parameters like:
{
    "name": "TestError.xml", 
    "variables": { }
}

You should see as the request response a stack trace like the one displayed.

The problem is to keep a correct JSON format in case of error, characters should be properly escaped.

**Comment by laurentpellegrino** [comment]
Linked with https://github.com/ow2-proactive/scheduling/issues/2245.

**Comment by laurentpellegrino** [comment]
Missing double quotes for value + escaping.
